services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    env_file:
      - .env.production
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postiva.entrypoints=websecure"
      - "traefik.http.routers.postiva.tls.certResolver=letsencrypt"
      - "traefik.http.routers.postiva.rule=Host(`postiva.app`) || Host(`dash.postiva.app`)"
      - "traefik.http.services.postiva.loadbalancer.server.port=4000"
    ports:
      - 4000:4000

networks:
  dokploy-network:
    external: true
