services:
  web:
    build:
      context: .
      dockerfile: ./apps/landing/Dockerfile
    restart: always
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.taskion.entrypoints=websecure"
      - "traefik.http.routers.taskion.tls.certResolver=letsencrypt"
      - "traefik.http.routers.taskion.rule=Host(`taskion.app`)"
      - "traefik.http.services.taskion.loadbalancer.server.port=7000"
    ports:
      - 7000:7000

networks:
  dokploy-network:
    external: true
