services:
  web:
    build:
      context: .
      dockerfile: ./apps/landing/Dockerfile
    restart: always
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postiva.entrypoints=websecure"
      - "traefik.http.routers.postiva.tls.certResolver=letsencrypt"
      - "traefik.http.routers.postiva.rule=Host(`taskion.app`)"
      - "traefik.http.services.postiva.loadbalancer.server.port=4000"
    ports:
      - 4000:4000

networks:
  dokploy-network:
    external: true
